name: PR Coverage Report

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode
        with:
          IS_DESKTOP_BUILD: true

      - name: Install dependencies (PR branch)
        run: npm ci

      - name: Run Jest coverage (PR branch)
        run: npm test -- --coverage --coverageReporters=json-summary

      - name: Save PR branch coverage summary
        run: cp coverage/coverage-summary.json pr-coverage-summary.json

      - name: Upload Jest HTML coverage report (PR branch)
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-pr
          path: coverage/lcov-report/

      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git checkout ${{ github.event.pull_request.base.ref }}

      - name: Install dependencies (base branch)
        run: npm ci

      - name: Run Jest coverage (base branch)
        run: npm test -- --coverage --coverageReporters=json-summary

      - name: Save base branch coverage summary
        run: cp coverage/coverage-summary.json base-coverage-summary.json

      - name: Upload Jest HTML coverage report (base branch)
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-base
          path: coverage/lcov-report/

      - name: Upload coverage summaries
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-summaries
          path: |
            base-coverage-summary.json
            pr-coverage-summary.json

      - name: Run octocov-action
        uses: k1LoW/octocov-action@v1

      # - name: Update PR with Coverage Section
      #   uses: ./.github/actions/javascript/updateCoverageSection
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 